[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "concurrent_loop"
version = "1.1.4"
authors = [
  { name="KC Lee", email="lathe-rebuke.0c@icloud.com" },
]
description = "Helper for running functions in a concurrent loop."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://bitbucket.org/kclee/concurrent/src/master/"